name: "Publish Dev Containers"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish Base Dev Container
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     imageName: ghcr.io/${{ github.repository }}/base
      #     imageTag: 0.1.0
      #     subFolder: base
      #     platform: linux/arm64,linux/amd64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: List builder instances
        run: docker buildx ls

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/base
          imageTag: 0.1.0,latest
          subFolder: base
          platform: linux/arm64,linux/amd64
          push: always