name: "Publish Dev Containers"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container: ghcr.io/j2udev/devcontainers/devcontainer-ide:0
    permissions:
      packages: write
    strategy:
      matrix:
        devcontainer:
          - folder: base
            tags: 0.3.1,0.3,0,latest
          - folder: devcontainer-ide
            tags: 0.1.0,0.1,0,latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}/${{ matrix.devcontainer.folder }}
          imageTag: ${{ matrix.devcontainer.tags }}
          subFolder: ${{ matrix.devcontainer.folder }}
          platform: linux/arm64,linux/amd64
          push: always